#!/usr/bin/env python3
"""Regenerates assets/ for the architecture dossier from its real sources.

Run from this directory: python3 prepare_assets.py

What's reproducible from files already in this repo:
  - fig-scenetree.svg / fig-uml.svg  <- rendered here from diagrams/*.dot
    (Graphviz; `dot` must be on PATH). SVG, not PNG: a large embedded raster
    PNG here was found to corrupt the "Dossier <-> Godot-Editor" print-color
    toggle for every .code block on a LATER page in Chrome's print-to-pdf
    pipeline (reproduced down to a minimal case; a modest ~60 KB quantized
    PNG still triggered it, an SVG of the same diagram did not) — keep these
    two diagrams as SVG, don't "optimize" back to PNG without re-testing the
    toggle across the whole document.
  - tetris-icon.png                  <- copied from the app's own launcher
    icon (tetris-icon 432x432.png in the project root)

What ISN'T reproducible by this script (kept only as the already-processed
files already sitting in assets/ — this script leaves them alone):
  - fig-gameplay.png / fig-rebind.png / fig-aim.png / fig-goal.png — real
    screenshots captured live off an actually-running windowed instance of
    the game (godot --path projects/tetris, NOT --editor, on the same X
    display this session runs on) during the 2026-09-16 session, driven via
    xdotool (mouse moves/clicks, mouse wheel for help paging) and captured
    with `import -window <id>`. Recapturing them needs a live run of the
    game and some manual play (build a stack, open Settings -> Controls,
    open How to Play and page to "Aim & auto-rotate" / "Goal & scoring");
    there's nothing to "run" here as a batch script.
"""

import shutil
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
TETRIS_ROOT = HERE.parent.parent
ASSETS = HERE / "assets"
DIAGRAMS = HERE / "diagrams"

ASSETS.mkdir(exist_ok=True)


def render_diagram(dot_file: Path, out_file: Path) -> None:
    subprocess.run(
        ["dot", "-Tsvg", str(dot_file), "-o", str(out_file)],
        check=True,
    )
    print("rendered", out_file.relative_to(HERE))


def copy_asset(src: Path, dst: Path) -> None:
    shutil.copyfile(src, dst)
    print("copied", dst.relative_to(HERE), "<-", src)


def main() -> None:
    render_diagram(DIAGRAMS / "scenetree.dot", ASSETS / "fig-scenetree.svg")
    render_diagram(DIAGRAMS / "uml.dot", ASSETS / "fig-uml.svg")

    copy_asset(
        TETRIS_ROOT / "tetris-icon 432x432.png",
        ASSETS / "tetris-icon.png",
    )

    print(
        "\nfig-gameplay.png / fig-rebind.png / fig-aim.png / fig-goal.png left "
        "untouched — real screenshots from a live windowed run, not "
        "regenerated by this script (see the module docstring)."
    )


if __name__ == "__main__":
    main()
